# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
  param_fetcher_listener: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
      xml: true
  exception:
    serializer_error_renderer: true
    codes:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
      'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
